export const ICONS = {
  cloud: require('../assets/icons/cloud.png'),
  local: require('../assets/icons/local.png'),
  bell: require('../assets/icons/bell.png'),
  user: require('../assets/icons/user.png'),
  plus: require('../assets/icons/plus.png'),
  primary: require('../assets/icons/primary.png'),
  more: require('../assets/icons/more.png'),
  primarySquare: require('../assets/icons/primary-square.png'),
  secondarySquare: require('../assets/icons/secondary-square.png'),
  document: require('../assets/icons/document.png'),
  image: require('../assets/icons/image.png'),
  music: require('../assets/icons/music.png'),
  video: require('../assets/icons/video.png'),
  search: require('../assets/icons/search.png'),
  caretRight: require('../assets/icons/caret-right.png'),
  singin: require('../assets/icons/singin.png'),
};
